boatparty/models.py
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from boatparty import db, login_manager


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


class GuestBookPost(db.Model):
    __tablename__ = 'guest_book_posts'
    id = db.Column(db.Integer, primary_key=True)
    posted_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    name = db.Column(db.String(80), unique=True, nullable=False)
    post_md = db.Column(db.Text, nullable=False)
    post_html = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return '<GuestBookPosts {} {} {}>'.format(self.id, self.posted_at, self.name)


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(30), nullable=False)

    def __repr__(self):
        return '<Users {} {}>'.format(self.id, self.username)

boatparty/forms.py
from flask_wtf import FlaskForm
from flask_wtf.recaptcha import RecaptchaField
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, ValidationError, Email
from flask_pagedown.fields import PageDownField
from boatparty.models import GuestBookPost


class GuestBookForm(FlaskForm):
    name = StringField('Your Name', validators=[DataRequired()])
    pagedown = PageDownField('Please leave us a note!\n Markdown supported!')
    recaptcha = RecaptchaField()
    submit = SubmitField('Good to Go!')

    def validate_name(self, name):
        name = GuestBookPost.query.filter_by(name=name.data).first()
        if name:
            raise ValidationError(
                "Looks like you've left us a note already! Let's save some space for others!")


class FAQForm(FlaskForm):
    name = StringField('Your Name', validators=[DataRequired()])
    question = StringField('Your Question', validators=[DataRequired()])
    send = SubmitField('Send')


class AdminForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Passord', validators=[DataRequired()])
    login = SubmitField('Login')

boatparty/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_pagedown import PageDown
from flask_mail import Mail
from flask_moment import Moment
from flask_login import LoginManager
from config import Config


db = SQLAlchemy()
migrate = Migrate()
pagedown = PageDown()
mail = Mail()
moment = Moment()
login_manager = LoginManager()


def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(config)

    db.init_app(app)
    migrate.init_app(app, db)
    pagedown.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    login_manager.init_app(app)

    from boatparty.routes import main
    app.register_blueprint(main)

    from boatparty.errors import error
    app.register_blueprint(error)

    return app

boatparty/routes.py
from flask import render_template, url_for, redirect, flash, Blueprint
from flask_mail import Message
from flask_login import login_user, current_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from boatparty import db
from boatparty.forms import GuestBookForm, FAQForm, AdminForm
from boatparty.models import GuestBookPost, User
from boatparty.utils import (convert_markdown_to_html,
                             send_email_notification,
                             get_countdown_data,
                             get_gallery_photos)


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def index():
    """Home View"""
    title = 'Home'

    data = get_countdown_data()
    return render_template('home.html', title=title, **data)


@main.route('/photos')
def photos():
    """Photos View"""
    title = 'Photos'

    gallery = get_gallery_photos()
    return render_template('photos.html', title=title, gallery=gallery)


@main.route('/the-big-day')
def the_big_day():
    """The Big Day View"""
    title = 'The Big Day'
    return render_template('the-big-day.html', title=title)


@main.route('/registry')
def registry():
    """Registry View"""
    title = 'Registry'
    return render_template('registry.html', title=title)


@main.route('/guest-book', methods=['GET', 'POST'])
def guest_book():
    """Guest Book View"""
    form = GuestBookForm()
    title = 'Guest Book'

    posts = GuestBookPost.query.order_by(GuestBookPost.posted_at.desc()).all()
    if form.validate_on_submit():
        name = form.name.data
        post_md = form.pagedown.data
        post_html = convert_markdown_to_html(form.pagedown.data)

        post = GuestBookPost(name=name, post_md=post_md, post_html=post_html)

        db.session.add(post)
        db.session.commit()

        send_email_notification(name, post_html, 'guest book post')

        flash('Thanks for leaving us a note!')
        return redirect(url_for('main.guest_book'))
    return render_template('guest-book.html', title=title, form=form, posts=posts)


@main.route('/where-to-stay')
def where_to_stay():
    """Where to Stay View"""
    title = 'Where to Stay'
    return render_template('where-to-stay.html', title=title)


@main.route('/faq', methods=['GET', 'POST'])
def faq():
    """FAQ View"""
    title = 'Frequently Asked Questions'
    form = FAQForm()

    if form.validate_on_submit():
        name = form.name.data
        message = form.question.data

        send_email_notification(name, message, 'question')

        flash("Thanks for the note! We'll take a look and send you an update as soon as we can!")
        return redirect(url_for('main.faq'))
    return render_template('faq.html', title=title, form=form)


@main.route('/admin', methods=['GET', 'POST'])
def admin():
    """Site Admin Suite Login"""
    title = 'Site Admin Login'
    form = AdminForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            flash('Successfully logged into Admin Mode!')
            return redirect(url_for('main.guest_book'))
        else:
            flash('Something went wrong with your login!')
    return render_template('admin.html', title=title, form=form)


@main.route('/base')
def base_test():
    """Temporary route for checking the base template."""
    return render_template('base.html')


@main.route('/logout')
def logout():
    """A route used to log out of admin mode"""
    logout_user()
    flash('Successfully logged out of Admin Mode!')
    return redirect(url_for('main.guest_book'))


@main.route('/delete/<int:post_id>',  methods=['POST'])
@login_required
def delete(post_id):
    post = GuestBookPost.query.filter_by(id=int(post_id)).first()

    db.session.delete(post)
    db.session.commit()

    flash('Successfully deleted the Post!')
    return redirect(url_for('main.guest_book'))

boatparty/templates/about.html
{% extends 'base.html' %}

{% block extra_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
{% endblock %}

{% block app_content %}
<h1>About Us</h1>

<p>We'll have some text about how we met and all that cheesy stuff. We might even put in some info about the wedding
    party if we're feeling up to it!</p>

<div class="photo-gallery">
    <div class="container">
        <div class="row photos">
            {% for g in gallery %}
            <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="static/img/gallery/{{ g }}"
                    data-lightbox="photos"><img class="img-fluid" src="static/img/gallery/{{ g }}"></a></div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
{% endblock %}

boatparty/templates/admin.html
{% extends 'base.html' %}

{% block home_content %}

<div id="background-image">
    <div class="container-fluid d-flex align-items-center justify-content-center h-100">
        <div class="row justify-content-center text-center w-100">
            <div class="col-md-3 col-sm-6">
                <h1 class="text-white hello home">Site Admin</h1>
                <form method="POST" action="{{ url_for('main.admin') }}">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group mb-1">
                            {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-md is-invalid") }}
                            <div class="invalid-feedback font-weight-bold">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.email(class="form-control form-control-md", placeholder="Email") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password(class="form-control form-control-md", placeholder="Password") }}
                        </div>
                            {{ form.login(class="btn btn-light") }}
                    </fieldset>
                </form>
                </h4>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_js %}
{{ moment.include_moment() }}
{% endblock %}

boatparty/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% if title %}Nick & Natalie - {{ title }} {% else %} Nick & Natalie {% endif %}
        {% endblock %}
    </title>
    <link rel="icon" href="{{url_for('static', filename='icons/favicon-N+N-white.png')}}" type="image/png"
        sizes="32x32">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156198148-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-156198148-1');
    </script>

    {% block extra_css %}{% endblock %}

</head>

<body>

    {% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('main.the_big_day') }}">The Big Day</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('main.where_to_stay') }}">Where to Stay</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('main.faq') }}">FAQ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('main.registry') }}">Registry</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('main.photos') }}">Photos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('main.guest_book') }}">Guest Book</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('main.logout') }}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% endblock %}

    {% if title in ['Home', 'Site Admin Login'] %}

    {% block home_content %}{% endblock %}

    {% else %}
    <div class="container py-3">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info alert-dismissible" role="alert">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}

        {% block app_content %}{% endblock %}

    </div>
    {% endif %}
    <footer class="mastfoot bg-dark py-3">
        <div class="text-center">
            <img class="mb-1" src="{{ url_for('static', filename='icons/N+N-white.png') }}" alt="">
            <p class="text-white"><small>Designed by Natty & <a href="https://github.com/nickbap/BoatParty"
                        target="_blank" class="text-info">Created</a> by Nick</small></p>
        </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

    {% block extra_js %}{% endblock %}

</body>

</html>

boatparty/templates/details.html
{% extends 'base.html' %}

{% block app_content %}

<h1>Details</h1>
<p>Here's what to expect on our wedding weekend. We can't wait to celebrate with you!</p>
<div class="row align-items-center mt-5">
    <div class="col-sm-6 text-center">
        <h4>Ceremony</h4>
        <p>Saturday, August 1, 2020</p>
        <p>4:30pm</p>
    </div>
    <div class="col-sm-6 text-center">
        <img src="{{ url_for('static', filename='icons/floral.png') }}" alt="">
        <p>Marin Art & Garden Center</p>
        <address>30 Sir Francis Drake Blvd., Ross, CA 94957</address>
        <p>The Ceremony should last about 30 minutes. Cocktail Hour to follow. Please note that the Ceremony takes place
            on Grass so be careful with your shoes.</p>
        <a class="btn btn-info" target="_blank"
            href="https://www.google.com/maps/place/Marin+Art+%26+Garden+Center/@37.9627604,-122.5578252,16z/data=!4m5!3m4!1s0x808597495de32a3f:0x67d1228447e3c382!8m2!3d37.9634413!4d-122.5556122"
            role="button">Map</a>
    </div>
</div>
<div class="row align-items-center mt-5">
    <div class="col-sm-6 text-center">
        <h4>Reception</h4>
        <p>Saturday, August 1, 2020</p>
        <p>6:00pm to 10:00pm</p>
    </div>
    <div class="col-sm-6 text-center">
        <img src="{{ url_for('static', filename='icons/place-setting.png') }}" alt="">
        <p>Marin Art & Garden Center</p>
        <address>30 Sir Francis Drake Blvd., Ross, CA 94957</address>
        <p>The Reception will take place outside. It can be a bit chilly so considering bringing a light jacket. The
            night will consistent of dinner, drinks, and dancing. What else can you ask for with the people we love?!
        </p>
    </div>
</div>

{% endblock %}

boatparty/templates/email-notification.html
<p>Hey Nick and Natalie,</p>
<p><b><i>{{ name }}</i></b> just left you a new {{ notification_type }}:</p>
<hr>
<div>
    {{ message | safe }}
</div>
<hr>
<p>Thanks,</p>
<p>The Boat Party Website</p>

boatparty/templates/email_notification.html
<p>Hey Nick and Natalie,</p>
<p><b><i>{{ name }}</i></b> just left you a new Guest Book message:</p>
<hr>
<div>
    {{ post | safe }}
</div>
<hr>
<p>Thanks,</p>
<p>The Boat Party Website</p>

boatparty/templates/faq.html
{% extends 'base.html' %}

{% block app_content %}

<div class="text-center pt-3">
    <h1 class="hello">Frequently Asked Questions</h1>
    <p>Here's a list of Frequently Asked Questions and Answers!</p>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>What is the dress code?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>Cocktail Attire! Please remember it's an outdoor wedding with grass and gravel.</p>
    </div>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>Are kids invited?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>We love kids, but no, this wedding is for adults only.</p>
    </div>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>Is there a shuttle to and from the Ceremony? What about after?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>Yes! Here's the schedule:</p>
        <table class="table">
            <tbody>
                <tr>
                    <td>
                        <p>3:30PM</p>
                    </td>
                    <td>
                        <p>Shuttle Service starts at <a class="text-info" href="https://goo.gl/maps/C2DyvJbx4fe5UKw28"
                                target="_blank">Courtyard by Marriot Larkspur</a> to Marin Arts and Garden Center
                        </p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>8:30PM</p>
                    </td>
                    <td>
                        <p>Shuttle Service starts from Marin Arts and Garden Center to Courtyard by Marriot
                            Larkspur</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>9:30PM</p>
                    </td>
                    <td>
                        <p>Shuttle Service starts from Marin Arts and Garden Center to <a class="text-info"
                                href="https://goo.gl/maps/DQHTCBnE7jChGdsb9" target="_blank">Log Cabin Dugout Bar</a>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>1:30AM</p>
                    </td>
                    <td>
                        <p>...If you're still alive, last shuttle to Courtyard by Marriot Larkspur</a>
                        </p>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>Can I bring a date?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>Only if your invitation says so!</p>
    </div>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>What time should I arrive at the venue?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>Please arrive between 4:00 & 4:15. The Bride will walk down the aisle at 4:30!</p>
    </div>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>Do you have any hotel recommendations?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>Yes! Please check out our <a class="text-info" href="{{ url_for('main.where_to_stay') }}">Where to
                Stay</a>
            page.
        </p>
    </div>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>Is there parking at the venue?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>Yes! There is a large parking lot at the Marin Art & Garden Center.</p>
    </div>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>Is the venue indoor & outdoor?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>The ceremony is outside on a lawn, the reception is on a gravel area, and the dance floor is indoors.
            Remember to
            wear comfortable shoes and a jacket in case it gets chilly!</p>
    </div>
</div>
<div class="row py-5">
    <div class="col-sm-6 text-center">
        <h2 class="hello">Q:</h2>
        <p>Any recommendations for things to do in the area?</p>
    </div>
    <div class="col-sm-6 text-center border-left">
        <h2 class="hello">A:</h2>
        <p>Yes! Here's a <a class="text-info" href="https://www.pinterest.com/nbautista12/august-28th-2021/"
                target="_blank">Pinterest</a>
            Board (shameless plug) of some of our favorites places we've enjoyed over the years.</p>
    </div>
</div>
<div class="container-fluid mt-3">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-8">
            <div class="text-center">
                <p>If you think of something we left off, please shoot us an email below!</p>
            </div>

            <form method="POST" action="{{ url_for('main.faq')}}">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.name.label(class="form-control-label") }}
                        {{ form.name(class="form-control form-control-md") }}
                    </div>
                    <div class="form-group">
                        {{ form.question.label(class="form-control-label") }}
                        {{ form.question(class="form-control form-control-md") }}
                    </div>
                    {{ form.send(class="btn btn-light") }}
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock %}

boatparty/templates/guest-book.html
{% extends 'base.html' %}

{% block app_content %}
<div class="pt-3">
    <h1 class="hello">Guest Book</h1>
    <p>Feel free to leave us a note! If you want to get fancy, you can use <a target="_blank"
            href="https://www.markdownguide.org/cheat-sheet/">Markdown</a> in the form below.</p>
</div>
<form method="POST" action="{{ url_for('main.guest_book')}}">
    {{ form.hidden_tag() }}
    {{ form.csrf_token }}
    <fieldset class="form-group">
        <div class="form-group">
            {{ form.name.label(class="form-control-label") }}
            {% if form.name.errors %}
            {{ form.name(class="form-control form-control-md is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.name.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.name(class="form-control form-control-md") }}
                {% endif%}
            </div>
            <div class="form-group">
                {{ form.pagedown.label(class="form-control-label") }}
                {{ form.pagedown(class="form-control form-control-md") }}
                <div class="mt-1">
                    {% for error in form.recaptcha.errors %}
                    {{ error }}
                    {% endfor %}
                    {{ form.recaptcha }}
                </div>
            </div>
    </fieldset>
    <div class="form-group">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-light" data-toggle="modal" data-target="#postWarningModal">
            Post
        </button>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="postWarningModal" tabindex="-1" role="dialog" aria-labelledby="postWarningModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="postWarningModalLabel">Wait!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Please remember that our family will be reading these posts so we ask that you keep it PG!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hm, I'll double-check.</button>
                    {{ form.submit(class="btn btn-light") }}
                </div>
            </div>
        </div>
    </div>
</form>

<div class="guest-book">
    {% for post in posts %}
    <hr>
    <p>Posted {{ moment(post.posted_at).fromNow() }} <br>
        <i>{{ post.name }}</i> said:</p>
    {{ post.post_html | safe }}

    {% if current_user.is_authenticated %}
    <form action="{{ url_for('main.delete', post_id=post.id) }}" method="POST">
        <div class="form-group">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger" data-toggle="modal"
                data-target="#postDeleteWarningModal{{ post.id }}">
                Delete
            </button>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="postDeleteWarningModal{{ post.id }}" tabindex="-1" role="dialog"
            aria-labelledby="postDeleteWarningModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="postDeleteWarningModalLabel">Wait!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want delete this post?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </div>
                </div>
            </div>
        </div>

    </form>
    {% endif %}

    {% endfor %}
</div>
{% endblock %}

{% block extra_js %}
{{ pagedown.include_pagedown() }}
{{ moment.include_moment() }}
{% endblock %}

boatparty/templates/guest_book.html
{% extends 'base.html' %}

{% block app_content %}
<h1>Guest Book</h1>

<p>This page will have a guestbook that I plan to build.</p>

<form method="POST" action="{{ url_for('main.guest_book')}}">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <div class="form-group">
            {{ form.name.label(class="form-control-label") }}
            {{ form.name(class="form-control form-control-md") }}
        </div>
        <div class="form-group">
            {{ form.pagedown.label(class="form-control-label") }}
            {{ form.pagedown(class="form-control form-control-md") }}
        </div>
    </fieldset>
    <div class="form-group">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-light" data-toggle="modal" data-target="#postWarningModal">
            Post
        </button>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="postWarningModal" tabindex="-1" role="dialog" aria-labelledby="postWarningModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="postWarningModalLabel">Wait!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Please remember that our family will be reading these posts so we ask that you keep it PG!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hm, I'll double-check.</button>
                    {{ form.submit(class="btn btn-light") }}
                </div>
            </div>
        </div>
    </div>
</form>

<div>
    {% for post in posts %}
    <hr>
    <p>Posted {{ moment(post.posted_at).fromNow() }} <br>
        <i>{{ post.name }}</i> said:</p>
    {{ post.post_html | safe }}

    {% endfor %}
</div>
{% endblock %}

{% block extra_js %}
{{ pagedown.include_pagedown() }}
{{ moment.include_moment() }}
{% endblock %}